FROM swipl

LABEL version="1.0"
LABEL maintainer="Yuto Chikazawa <minet6759@gmail.com>"
LABEL description="Advanced lecture on programming languages."

RUN apt-get update && \
    apt-get install -y -y --no-install-recommends \
        vim

WORKDIR /usr/src
